### ISSUE TITLE
Project requirements for the class class

### ISSUE THREAD

**Issue by xhanio** [cs690/spring2015-datavis#1]
Can you provide some ideas about how to answer these questions below?

The core functionality of the project.
What you definitely need to complete by the end of the semester.
The extra functionality of your project.
What will be completed only if there is time.
Important quality attributes.

**Comment by sjengle** [comment]
We discussed this a bit in the meeting. It might be a good idea to start taking notes.
- Multiple interactive and linked visualizations implemented in D3 of the specified dataset.
- At least 1 user-tested visualization, and 3 other visualizations of the data.
- Additional visualizations, more sophisticated techniques.
- I don't see how this and the second bullet are different.
- Usability, accuracy/correctness
