### ISSUE TITLE
Video Categories

### ISSUE THREAD

**Issue by xhanio** [cs690/spring2015-datavis#3]
We have about 12 category values of "category" attribute in the YouTube dataset, and we plan to reduce them into about 3-5 bins. The categories are listed below:
1. Film & Animation
2. News & Politics
3. Entertainment
4. Sports
5. Comedy
6. Music
7. Howto & DIY
8. Pets & Animals
9. People & Blog
10. Autos & Vehicles
11. Gadgets & Games
12. Travel & Places

Could you please give us an idea that how to split them? Thanks!

**Comment by sjengle** [comment]
Why 3 to 5 bins? Did you choose that number arbitrarily, or do you have a reason behind it?

I suggest you look at how many videos fall into each category. Those with lots of videos you might want to keep separate, and those with relatively few you may want to combine into a "Miscellaneous" or "Other" category.
